# 1st stage, build the app
FROM maven:3.8.4-openjdk-17-slim as build

WORKDIR /helidon

# Create a first layer to cache the "Maven World" in the local repository.
# Incremental docker builds will always resume after that, unless you update
# the pom
ADD pom.xml .
{{#module-poms}}
ADD {{.}} {{.}}
{{/module-poms}}
RUN mvn package -Dmaven.test.skip -Declipselink.weave.skip {{phase1-options}}

# Do the Maven build!
# Incremental docker builds will resume here when you change sources
ADD src src
{{#module-dirs}}
ADD {{.}} {{.}}
{{/module-dirs}}
RUN mvn package -DskipTests

RUN echo "done!"

# 2nd stage, build the runtime image
FROM openjdk:17-jdk-slim
WORKDIR /helidon

# Copy the binary built in the 1st stage
COPY --from=build /helidon/{{artifact-path}}/{{artifact-name}}.jar ./
COPY --from=build /helidon/{{artifact-path}}/libs ./libs

CMD ["java", "-jar", "{{artifact-name}}.jar"]

EXPOSE 8080
