///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

// TODO check javadoc for health check (both helidon and microprofile)
// TODO check microprofile spec for health check

= Health Checks
:description: Helidon health checks
:keywords: helidon, health-checks, health, check

This document describes the health check API for Helidon SE.

== About health checks

It's a good practice to monitor your microservice's health in order to ensure
 it is available and performs correctly.

Health checks work with your application exposing health statuses and a
 tool that collects those statuses at regular intervals. Such tool is usually
 the deployment orchestrator, it analyses the collected statuses and takes
 action accordingly.

NOTE: Network traffic can be routed to new instances of your application based
 on health check statuses.

A typical health check combines the statuses of all the dependencies that can
 impact availability and the ability to perform correctly:

* Network latency
* Storage
* Database
* Other services used by your application

TIP: Be wise with the amount of collected information to avoid overloading the
 application and impacting users.

== API

The API allows to register multiple health checks that are combined and exposed
 in an HTTP endpoint at `/health`.

A health check is a function that reports a state: `UP` or `DOWN` with a
 description.

The overall status is computed from all the registered health checks and mapped
 to a response code:

* `200`: all health checks succeeded
* `503`: some health check failed
* `500`: an an error occurred while reporting the health

A set of built-ins health checks can be optionally enabled to report various
 health check statuses that are commonly used:

* Deadlock detection
* Available disk space
* Available heap memory

The API is composed of the following classes:

* `io.helidon.health.HealthSupport`: a WebServer Service class that contains all
 the registered health check functions and exposes `/health`
* `io.helidon.health.HealthSupport.Builder`: a builder class for `HealthSupport`
* `org.eclipse.microprofile.health.HealthCheckResponse`: a class that represents
 the result of a health check function, it contains a state and a description.
* `org.eclipse.microprofile.health.HealthCheckResponseBuilder` a builder class
 for `HealthCheckResponse`

NOTE: `HealthCheckResponse` and `HealthCheckResponseBuilder` are part of the
 MicroProfile API.

=== Prerequisites

Declare the following dependency in your project:

[source,xml]
----
    <dependency>
        <groupId>io.helidon.health</groupId>
        <artifactId>helidon-health</artifactId>
    </dependency>
----

=== Basic example

The following example registers a health check that is always `UP` with a
 description that contains the current time in milliseconds.

[source,java]
----
HealthSupport health = HealthSuport.builder()
    .add(() -> HealthCheckResponse.named("exampleHealthCheck")
                 .up()
                 .withData("time", System.currentTimeMillis())
                 .build())                          // <1>
    .build();

Routing.builder()
        .register(JsonSupport.create()) // <2>
        .register(health) // <3>
        .build();
----
<1> Add a custom health check. This example returns `UP` and current time
<2> Enable support for `JSON`
<3> Register health support with web server routing (adds the `/health` endpoint)

You can get health-check data through the `/health` endpoint.

The following is an example of the response (in JSON format) to a health-check
 request, based on the snippet above:

[source,json]
----
{
    "outcome": "UP",
    "checks": [
        {
            "name": "exampleHealthCheck",
            "state": "UP",
            "data": {
                "time": 1546958376613
            }
        }
    ]
}
----

=== Built-in health-check

To enable the built-in health checks, add the following dependency:

[source,xml]
----
    <dependency>
        <groupId>io.helidon.health</groupId>
        <artifactId>helidon-health-checks</artifactId>
    </dependency>
----

The following example registers the built-in health checks.

[source,java]
----
HealthSupport health = HealthSuport.builder()
    .add(HealthChecks.healthChecks()) // <1>
    .build();

Routing.builder()
        .register(JsonSupport.create()) // <2>
        .register(health) // <3>
        .build();
----
<1> Add built-in health checks (requires the `helidon-health-checks` dependency)
<2> Enable support for `JSON`
<3> Register health support with web server routing (adds the `/health` endpoint)

The response looks as follow:

[source,json]
----
{
    "outcome": "UP",
    "checks": [
        {
            "name": "deadlock",
            "state": "UP"
        },
        {
            "name": "diskSpace",
            "state": "UP",
            "data": {
                "free": "211.00 GB",
                "freeBytes": 226563444736,
                "percentFree": "45.31%",
                "total": "465.72 GB",
                "totalBytes": 500068036608
            }
        },
        {
            "name": "heapMemory",
            "state": "UP",
            "data": {
                "free": "215.15 MB",
                "freeBytes": 225600496,
                "max": "3.56 GB",
                "maxBytes": 3817865216,
                "percentFree": "99.17%",
                "total": "245.50 MB",
                "totalBytes": 257425408
            }
        }
    ]
}
----
