///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Kubernetes Probes
:description: Kubernetes probes
:keywords: helidon, readiness, liveliness, probes, kubernetes

== Health with Kubernetes

A well-behaved microservice reports on its own health.
Two common approaches for checking health, often used together, are:

* readiness - a simple verification that the service has been started, has
 initialized itself, and is ready to respond to requests; and
* liveness - often a more thorough assessment of whether
and how well the service can do its job.

For example, Kubernetes can ping your service's readiness endpoint after it
 starts the pod containing the service to determine when the service is ready to
 accept requests, withholding traffic until the readiness endpoint reports
 success.

Kubernetes can use the liveness endpoint to find out if the service considers
 itself able to function, attempting a pod restart if the endpoint reports a
 problem.

In general a liveness check might assess:

- service health - whether the service itself can do its job correctly
- host health - if the host has sufficient resources (for example, disk space)
for the service to operate
- health of other, dependent services - if other services on which this service
depends are themselves OK.

We will add an app-specific liveness check. Our greeting service does not depend
 on any host resources (like disk space) or any other services. So for this
example we define our service as "alive" in a very trivial way:
if the greeting text has been assigned
_and is not empty_ when trimmed of leading or trailing white space. Otherwise we
consider the service to be unhealthy, in which case the service will
still respond but its answers might not be what we want.

Normally we would
write our service to make
sure that a newly-assigned greeting is non-empty _before_
accepting it. But omitting that validation lets us create an easy health check
that we can use by simply setting the greeting to blank from
a `curl` command.